# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'ChallengeOne' do
pod 'AFNetworking', '~> 3.1'
pod 'SVProgressHUD', '~> 2.0'
end

target 'ChallengeOneTests' do

end

