# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'SharePics' do
pod 'Firebase'
pod 'Firebase/Database'
pod 'FirebaseAuth'
end

target 'SharePicsTests' do

end

target 'SharePicsUITests' do

end

